from bing_image_downloader import downloader
import os

# Define search queries
search_queries = ['Shreyas Talpade HD Face',
 'Shruti Haasan HD Face',
 'Shyam Benegal HD Face',
 'Sidharth Malhotra HD Face',
 'Smita Patil HD Face',
 'Smriti Irani HD Face',
 'Sonakshi Sinha HD Face',
 'Sonam Kapoor HD Face',
 'Sonia Gandhi HD Face',
 'Sonu Nigam HD Face',
 'Soumitra Chatterjee HD Face',
 'Sridevi HD Face',
 'Srishti Shrivastava HD Face',
 'Subhash Chandra Bose HD Face',
 'Sumeet Vyas HD Face',
 'Sunil Chhetri HD Face',
 'Sunil Shetty HD Face',
 'Sunny Deol HD Face',
 'Suresh Raina HD Face',
 'Suriya HD Face',
 'Sushant Singh Rajput HD Face',
 'Taapsee Pannu HD Face',
 'Tabu HD Face',
 'Tamannaah Bhatia HD Face',
 'Tamannaah Bhatia HD Face',
 'Tiger Shroff HD Face',
 'Tinnu Anand HD Face',
 'Tom Cruise HD Face',
 'Tom Hanks HD Face',
 'Trupti Khamkar HD Face',
 'Tusshar Kapoor HD Face',
 'Uday Chopra HD Face',
 'Uddhav Thackeray HD Face',
 'Ujjwal Chaurasia HD Face',
 'Utpal Dutt HD Face',
 'Vaani Kapoor HD Face',
 'Varun Dhawan HD Face',
 'Veer Rajwant Singh HD Face',
 'Vicky Kaushal HD Face',
 'Vidya Balan HD Face',
 'Vijay Thalapathy HD Face',
 'Vijay Deverakonda HD Face',
 'Vijay Sethupathi HD Face',
 'Vijay Varma HD Face',
 'Vikram HD Face',
 'Vikrant Massey HD Face',
 'Vin Diesel HD Face',
 'Vineeta Singh HD Face',
 'Vinod Khanna HD Face',
 'Virat Kohli HD Face',
 'Virgil van Dijk HD Face',
 'Viswanathan Anand HD Face',
 'Vivek Oberoi HD Face',
 'Vsauce HD Face',
 'Waheeda Rehman HD Face',
 'Will Smith HD Face',
 'Yami Gautam HD Face',
 'Yash HD Face',
 'Yogi Adityanath HD Face',
 'Yuvraj Singh HD Face',
 'Zakir Khan HD Face',
 'Zareen Khan HD Face',
 'Zarina Wahab HD Face',
 'Zayn Saifi (Round2hell) HD Face',
 'Zeenat Aman HD Face',
 'Zoe Saldana HD Face',
 'Zoella HD Face',
]

#Loop through each search query
for query in search_queries:
    # Download images
    downloader.download(query, limit=25,  output_dir='dataset', adult_filter_off=True, force_replace=False, timeout=220, verbose=True)

    # Filter images to keep only those with .jpg extension
    download_dir = os.path.join('dataset', query.replace(' HD Face', ''))  # Remove "HD Face" from folder name
